### ISSUE TITLE
LDAP Connector doesn't recover groups

### ISSUE THREAD

**Issue by dairoca90** [OpenIdentityPlatform/OpenIDM#19]
**Describe the bug**
After configuration the ldap connector doesn't bring any group values.

**Screenshots**

<img width="1202" alt="Captura de Pantalla 2022-07-17 a la(s) 17 36 39" src="https://user-images.githubusercontent.com/38822740/179427573-131188c3-23d2-40f3-831f-92621b8040f7.png">

**Comment by vharseko** [comment]
@maximthomas 
http://localhost:8080/admin/org/forgerock/openidm/ui/admin/util/BackgridUtils.js
 = $1TypeError: filter.query is not a function. (In 'filter.query()', 'filter.query' is undefined)

<img width="1469" alt="Снимок экрана 2024-04-24 в 16 17 27" src="https://github.com/OpenIdentityPlatform/OpenIDM/assets/6818498/bf094b24-9e11-4974-8ffa-2031d1fa2296">
