### ISSUE TITLE
Binary version and Docker

### ISSUE THREAD

**Issue by lreiher** [OpenIdentityPlatform/OpenIDM#2]
Hey,

just asking, why do you not release a binary version and a corresponding Dockerfile for OpenIDM the same way you do with OpenDJ, OpenAM, OpenIG, ...?

Thanks!

**Comment by vharseko** [comment]
> release a binary version

https://github.com/OpenIdentityPlatform/OpenIDM/releases

> Dockerfile

https://hub.docker.com/r/openidentityplatform/openidm
