### ISSUE TITLE
When the docker environment is running OpenIDM, the LDAP connector configuration cannot be saved

### ISSUE THREAD

**Issue by caoguozhen** [OpenIdentityPlatform/OpenIDM#57]
![image](https://github.com/user-attachments/assets/c74320dc-e740-48b6-8b9b-e0e490a3783f)

**Comment by vharseko** [comment]
@caoguozhen  please check [openidentityplatform/openidm:6.1.1](https://hub.docker.com/layers/openidentityplatform/openidm/6.1.1/images/sha256-b169523dd05e3cbb72dbab4ddd8eea1857c12305a721a6c4f46789d3439934ec?context=explore)
